version: '3'

services:
  web:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - ./database:/usr/src/app/database
    links:
    - elasticsearch
    depends_on:
    - elasticsearch

  elasticsearch:
    image: elasticsearch
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./database:/usr/share/elasticsearch/data