web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  links:
    - elasticsearch
  volumes:
    - ./data:/data
  ports:
    - "8000:8000"

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"